; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "SFProBrows"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "HfdSwimmingTimeHardwareAndSoftwareCorporation"
#define MyAppURL "https://github.com/PyNetCoder/SFProBrows"
#define MyAppExeName "SFProBrows.exe"

[Setup]
AppId={{C3863AD1-24DE-42DA-A95A-0A19DEB377FB}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
LicenseFile=C:\Users\PC\Desktop\SFProBrows\LICENSE
PrivilegesRequiredOverridesAllowed=dialog
OutputDir=C:\Users\PC\Desktop
OutputBaseFilename=SFProBrows-1.0.0-InstallerSetup
SetupIconFile=C:\Users\PC\Desktop\SFProBrows\SFProBrowsInstallerSetupIcon.ico
SolidCompression=yes
WizardStyle=modern dynamic

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "turkish"; MessagesFile: "compiler:Languages\Turkish.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\PC\Desktop\SFProBrows\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\PC\Desktop\SFProBrows\_internal\*"; DestDir: "{app}\_internal"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\PC\Desktop\SFProBrows\SfpbNetProj\*"; DestDir: "{app}\SfpbNetProj"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\PC\Desktop\SFProBrows\sfpb_core.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\PC\Desktop\SFProBrows\sfpb_engine.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\PC\Desktop\SFProBrows\sfpb_net.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\PC\Desktop\SFProBrows\sfpbNetProj.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\PC\Desktop\SFProBrows\SFProBrows 1.0.0.py"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\PC\Desktop\SFProBrows\sfprobrows_registry.reg"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\PC\Desktop\SFProBrows\SFProBrowsIcon.ico"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\PC\Desktop\SFProBrows\SFProBrowsInstallerSetupIcon.ico"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\PC\Desktop\SFProBrows\CHANGELOG.md"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\PC\Desktop\SFProBrows\LICENSE"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\PC\Desktop\SFProBrows\README.md"; DestDir: "{app}"; Flags: ignoreversion

[Registry]
; --- YÖNETİCİ (ADMIN) MODU İÇİN HKLM AYARLARI ---
Root: HKLM; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\SFProBrows.exe"; Flags: uninsdeletekeyifempty; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\SFProBrows.exe"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName}"; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\SFProBrows.exe"; ValueType: string; ValueName: "Path"; ValueData: "{app}\"; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\RegisteredApplications"; Flags: uninsdeletekeyifempty; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\RegisteredApplications"; ValueType: string; ValueName: "SFProBrows"; ValueData: "SOFTWARE\SFProBrows\Capabilities"; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\SFProBrows\Capabilities"; Flags: uninsdeletekeyifempty; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\SFProBrows\Capabilities"; ValueType: string; ValueName: "ApplicationName"; ValueData: "SFProBrows"; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\SFProBrows\Capabilities"; ValueType: string; ValueName: "ApplicationDescription"; ValueData: "HfdSwimmingTimeHardwareAndSoftwareCorporation tarafindan gelistirilen yuksek performansli web tarayici."; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\SFProBrows\Capabilities"; ValueType: string; ValueName: "ApplicationIcon"; ValueData: "{app}\SFProBrowsIcon.ico,0"; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\SFProBrows\Capabilities\FileAssociations"; Flags: uninsdeletekeyifempty; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\SFProBrows\Capabilities\FileAssociations"; ValueType: string; ValueName: ".html"; ValueData: "SFProBrowsHTML"; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\SFProBrows\Capabilities\FileAssociations"; ValueType: string; ValueName: ".htm"; ValueData: "SFProBrowsHTML"; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\SFProBrows\Capabilities\URLAssociations"; Flags: uninsdeletekeyifempty; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\SFProBrows\Capabilities\URLAssociations"; ValueType: string; ValueName: "http"; ValueData: "SFProBrowsHTML"; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\SFProBrows\Capabilities\URLAssociations"; ValueType: string; ValueName: "https"; ValueData: "SFProBrowsHTML"; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\Classes\SFProBrowsHTML"; Flags: uninsdeletekeyifempty; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\Classes\SFProBrowsHTML"; ValueType: string; ValueName: ""; ValueData: "SFProBrows HTML Document"; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\Classes\SFProBrowsHTML"; ValueType: string; ValueName: "FriendlyTypeName"; ValueData: "SFProBrows HTML Document"; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\Classes\SFProBrowsHTML\DefaultIcon"; Flags: uninsdeletekeyifempty; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\Classes\SFProBrowsHTML\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\SFProBrowsIcon.ico,0"; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\Classes\SFProBrowsHTML\shell\open\command"; Flags: uninsdeletekeyifempty; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\Classes\SFProBrowsHTML\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""; Flags: uninsdeletevalue; Check: IsAdminInstallMode

; --- KULLANICI (NON-ADMIN) MODU İÇİN HKCU AYARLARI ---
Root: HKCU; Subkey: "SOFTWARE\RegisteredApplications"; Flags: uninsdeletekeyifempty; Check: not IsAdminInstallMode
Root: HKCU; Subkey: "SOFTWARE\RegisteredApplications"; ValueType: string; ValueName: "SFProBrows"; ValueData: "SOFTWARE\SFProBrows\Capabilities"; Flags: uninsdeletevalue; Check: not IsAdminInstallMode
Root: HKCU; Subkey: "SOFTWARE\SFProBrows\Capabilities"; Flags: uninsdeletekeyifempty; Check: not IsAdminInstallMode
Root: HKCU; Subkey: "SOFTWARE\SFProBrows\Capabilities"; ValueType: string; ValueName: "ApplicationName"; ValueData: "SFProBrows"; Flags: uninsdeletevalue; Check: not IsAdminInstallMode
Root: HKCU; Subkey: "SOFTWARE\SFProBrows\Capabilities"; ValueType: string; ValueName: "ApplicationDescription"; ValueData: "HfdSwimmingTimeHardwareAndSoftwareCorporation tarafindan gelistirilen yuksek performansli web tarayici."; Flags: uninsdeletevalue; Check: not IsAdminInstallMode
Root: HKCU; Subkey: "SOFTWARE\SFProBrows\Capabilities"; ValueType: string; ValueName: "ApplicationIcon"; ValueData: "{app}\SFProBrowsIcon.ico,0"; Flags: uninsdeletevalue; Check: not IsAdminInstallMode
Root: HKCU; Subkey: "SOFTWARE\SFProBrows\Capabilities\FileAssociations"; Flags: uninsdeletekeyifempty; Check: not IsAdminInstallMode
Root: HKCU; Subkey: "SOFTWARE\SFProBrows\Capabilities\FileAssociations"; ValueType: string; ValueName: ".html"; ValueData: "SFProBrowsHTML"; Flags: uninsdeletevalue; Check: not IsAdminInstallMode
Root: HKCU; Subkey: "SOFTWARE\SFProBrows\Capabilities\FileAssociations"; ValueType: string; ValueName: ".htm"; ValueData: "SFProBrowsHTML"; Flags: uninsdeletevalue; Check: not IsAdminInstallMode
Root: HKCU; Subkey: "SOFTWARE\SFProBrows\Capabilities\URLAssociations"; Flags: uninsdeletekeyifempty; Check: not IsAdminInstallMode
Root: HKCU; Subkey: "SOFTWARE\RegisteredApplications"; ValueType: string; ValueName: "http"; ValueData: "SFProBrowsHTML"; Flags: uninsdeletevalue; Check: not IsAdminInstallMode
Root: HKCU; Subkey: "SOFTWARE\RegisteredApplications"; ValueType: string; ValueName: "https"; ValueData: "SFProBrowsHTML"; Flags: uninsdeletevalue; Check: not IsAdminInstallMode
Root: HKCU; Subkey: "SOFTWARE\Classes\SFProBrowsHTML"; Flags: uninsdeletekeyifempty; Check: not IsAdminInstallMode
Root: HKCU; Subkey: "SOFTWARE\Classes\SFProBrowsHTML"; ValueType: string; ValueName: ""; ValueData: "SFProBrows HTML Document"; Flags: uninsdeletevalue; Check: not IsAdminInstallMode
Root: HKCU; Subkey: "SOFTWARE\Classes\SFProBrowsHTML\shell\open\command"; Flags: uninsdeletekeyifempty; Check: not IsAdminInstallMode
Root: HKCU; Subkey: "SOFTWARE\Classes\SFProBrowsHTML\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""; Flags: uninsdeletevalue; Check: not IsAdminInstallMode

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent