; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "SFProBrows"
#define MyAppVersion "1.1.0"
#define MyAppPublisher "HfdSwimmingTimeHardwareAndSoftwareCorporation"
#define MyAppURL "https://github.com/PyNetCoder/SFProBrows"
#define MyAppExeName "SFProBrows.exe"

[Setup]
AppId={{C3863AD1-24DE-42DA-A95A-0A19DEB377FB}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
LicenseFile=SourceFiles\LICENSE
PrivilegesRequiredOverridesAllowed=dialog
OutputDir=C:\Users\PC\Desktop
OutputBaseFilename=SFProBrows-1.1.0-InstallerSetup
SetupIconFile=SourceFiles\SFProBrowsInstallerSetupIcon.ico
SolidCompression=yes
WizardStyle=modern dynamic
ChangesAssociations=yes


[Languages]
Name: "en"; MessagesFile: "compiler:Default.isl"
Name: "tr"; MessagesFile: "compiler:Languages\Turkish.isl"
Name: "de"; MessagesFile: "compiler:Languages\German.isl"
Name: "fr"; MessagesFile: "compiler:Languages\French.isl"
Name: "es"; MessagesFile: "compiler:Languages\Spanish.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; Ana çalıştırılabilir dosya
Source: "SourceFiles\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion

; Alt klasörler ve bağımlılıklar
Source: "SourceFiles\_internal\*"; DestDir: "{app}\_internal"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "SourceFiles\SfpbNetProj\*"; DestDir: "{app}\SfpbNetProj"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "SourceFiles\extensions\*"; DestDir: "{app}\extensions"; Flags: ignoreversion recursesubdirs createallsubdirs

; Kritik DLL motorları (Güncellemelerde kilitlenmeyi önlemek için restartreplace eklendi)
Source: "SourceFiles\sfpb_core.dll"; DestDir: "{app}"; Flags: ignoreversion restartreplace
Source: "SourceFiles\sfpb_engine.dll"; DestDir: "{app}"; Flags: ignoreversion restartreplace
Source: "SourceFiles\sfpb_net.dll"; DestDir: "{app}"; Flags: ignoreversion restartreplace
Source: "SourceFiles\sfpbNetProj.dll"; DestDir: "{app}"; Flags: ignoreversion restartreplace

; Tarayıcının ana uygulama ikonu ve dokümantasyon
Source: "SourceFiles\SFProBrowsIcon.ico"; DestDir: "{app}"; Flags: ignoreversion
Source: "SourceFiles\CHANGELOG.md"; DestDir: "{app}"; Flags: ignoreversion
Source: "SourceFiles\LICENSE"; DestDir: "{app}"; Flags: ignoreversion
Source: "SourceFiles\README.md"; DestDir: "{app}"; Flags: ignoreversion

; NOT: 'SFProBrows 1.1.0.py' kaynak kodu ve 'SFProBrowsInstallerSetupIcon.ico' 
; kurulum sihirbazı ikonu son kullanıcı güvenliği ve temiz kurulum için buradan kaldırılmıştır.


[Registry]
; --- YÖNETİCİ (ADMIN) MODU İÇİN HKLM AYARLARI ---
Root: HKLM; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\SFProBrows.exe"; Flags: uninsdeletekeyifempty; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\SFProBrows.exe"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName}"; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\SFProBrows.exe"; ValueType: string; ValueName: "Path"; ValueData: "{app}\"; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\RegisteredApplications"; Flags: uninsdeletekeyifempty; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\RegisteredApplications"; ValueType: string; ValueName: "SFProBrows"; ValueData: "SOFTWARE\SFProBrows\Capabilities"; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\SFProBrows\Capabilities"; Flags: uninsdeletekeyifempty; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\SFProBrows\Capabilities"; ValueType: string; ValueName: "ApplicationName"; ValueData: "SFProBrows"; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\SFProBrows\Capabilities"; ValueType: string; ValueName: "ApplicationDescription"; ValueData: "HfdSwimmingTimeHardwareAndSoftwareCorporation tarafindan gelistirilen yuksek performansli web tarayici."; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\SFProBrows\Capabilities"; ValueType: string; ValueName: "ApplicationIcon"; ValueData: "{app}\SFProBrowsIcon.ico,0"; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\SFProBrows\Capabilities\FileAssociations"; Flags: uninsdeletekeyifempty; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\SFProBrows\Capabilities\FileAssociations"; ValueType: string; ValueName: ".html"; ValueData: "SFProBrowsHTML"; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\SFProBrows\Capabilities\FileAssociations"; ValueType: string; ValueName: ".htm"; ValueData: "SFProBrowsHTML"; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\SFProBrows\Capabilities\URLAssociations"; Flags: uninsdeletekeyifempty; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\SFProBrows\Capabilities\URLAssociations"; ValueType: string; ValueName: "http"; ValueData: "SFProBrowsHTML"; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\SFProBrows\Capabilities\URLAssociations"; ValueType: string; ValueName: "https"; ValueData: "SFProBrowsHTML"; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\Classes\SFProBrowsHTML"; Flags: uninsdeletekeyifempty; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\Classes\SFProBrowsHTML"; ValueType: string; ValueName: ""; ValueData: "SFProBrows HTML Document"; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\Classes\SFProBrowsHTML"; ValueType: string; ValueName: "FriendlyTypeName"; ValueData: "SFProBrows HTML Document"; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\Classes\SFProBrowsHTML\DefaultIcon"; Flags: uninsdeletekeyifempty; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\Classes\SFProBrowsHTML\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\SFProBrowsIcon.ico,0"; Flags: uninsdeletevalue; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\Classes\SFProBrowsHTML\shell\open\command"; Flags: uninsdeletekeyifempty; Check: IsAdminInstallMode
Root: HKLM; Subkey: "SOFTWARE\Classes\SFProBrowsHTML\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""; Flags: uninsdeletevalue; Check: IsAdminInstallMode

; --- KULLANICI (NON-ADMIN) MODU İÇİN HKCU AYARLARI ---
Root: HKCU; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\SFProBrows.exe"; Flags: uninsdeletekeyifempty; Check: not IsAdminInstallMode
Root: HKCU; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\SFProBrows.exe"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName}"; Flags: uninsdeletevalue; Check: not IsAdminInstallMode
Root: HKCU; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\SFProBrows.exe"; ValueType: string; ValueName: "Path"; ValueData: "{app}\"; Flags: uninsdeletevalue; Check: not IsAdminInstallMode
Root: HKCU; Subkey: "SOFTWARE\RegisteredApplications"; Flags: uninsdeletekeyifempty; Check: not IsAdminInstallMode
Root: HKCU; Subkey: "SOFTWARE\RegisteredApplications"; ValueType: string; ValueName: "SFProBrows"; ValueData: "SOFTWARE\SFProBrows\Capabilities"; Flags: uninsdeletevalue; Check: not IsAdminInstallMode
Root: HKCU; Subkey: "SOFTWARE\SFProBrows\Capabilities"; Flags: uninsdeletekeyifempty; Check: not IsAdminInstallMode
Root: HKCU; Subkey: "SOFTWARE\SFProBrows\Capabilities"; ValueType: string; ValueName: "ApplicationName"; ValueData: "SFProBrows"; Flags: uninsdeletevalue; Check: not IsAdminInstallMode
Root: HKCU; Subkey: "SOFTWARE\SFProBrows\Capabilities"; ValueType: string; ValueName: "ApplicationDescription"; ValueData: "HfdSwimmingTimeHardwareAndSoftwareCorporation tarafindan gelistirilen yuksek performansli web tarayici."; Flags: uninsdeletevalue; Check: not IsAdminInstallMode
Root: HKCU; Subkey: "SOFTWARE\SFProBrows\Capabilities"; ValueType: string; ValueName: "ApplicationIcon"; ValueData: "{app}\SFProBrowsIcon.ico,0"; Flags: uninsdeletevalue; Check: not IsAdminInstallMode
Root: HKCU; Subkey: "SOFTWARE\SFProBrows\Capabilities\FileAssociations"; Flags: uninsdeletekeyifempty; Check: not IsAdminInstallMode
Root: HKCU; Subkey: "SOFTWARE\SFProBrows\Capabilities\FileAssociations"; ValueType: string; ValueName: ".html"; ValueData: "SFProBrowsHTML"; Flags: uninsdeletevalue; Check: not IsAdminInstallMode
Root: HKCU; Subkey: "SOFTWARE\SFProBrows\Capabilities\FileAssociations"; ValueType: string; ValueName: ".htm"; ValueData: "SFProBrowsHTML"; Flags: uninsdeletevalue; Check: not IsAdminInstallMode
Root: HKCU; Subkey: "SOFTWARE\SFProBrows\Capabilities\URLAssociations"; Flags: uninsdeletekeyifempty; Check: not IsAdminInstallMode
; HATA DÜZELTİLDİ: Subkey yolları RegisteredApplications yerine doğru konuma yönlendirildi
Root: HKCU; Subkey: "SOFTWARE\SFProBrows\Capabilities\URLAssociations"; ValueType: string; ValueName: "http"; ValueData: "SFProBrowsHTML"; Flags: uninsdeletevalue; Check: not IsAdminInstallMode
Root: HKCU; Subkey: "SOFTWARE\SFProBrows\Capabilities\URLAssociations"; ValueType: string; ValueName: "https"; ValueData: "SFProBrowsHTML"; Flags: uninsdeletevalue; Check: not IsAdminInstallMode
Root: HKCU; Subkey: "SOFTWARE\Classes\SFProBrowsHTML"; Flags: uninsdeletekeyifempty; Check: not IsAdminInstallMode
Root: HKCU; Subkey: "SOFTWARE\Classes\SFProBrowsHTML"; ValueType: string; ValueName: ""; ValueData: "SFProBrows HTML Document"; Flags: uninsdeletevalue; Check: not IsAdminInstallMode
; EKSİKLER TAMAMLANDI: HKCU için FriendlyTypeName ve DefaultIcon yapıları eklendi
Root: HKCU; Subkey: "SOFTWARE\Classes\SFProBrowsHTML"; ValueType: string; ValueName: "FriendlyTypeName"; ValueData: "SFProBrows HTML Document"; Flags: uninsdeletevalue; Check: not IsAdminInstallMode
Root: HKCU; Subkey: "SOFTWARE\Classes\SFProBrowsHTML\DefaultIcon"; Flags: uninsdeletekeyifempty; Check: not IsAdminInstallMode
Root: HKCU; Subkey: "SOFTWARE\Classes\SFProBrowsHTML\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\SFProBrowsIcon.ico,0"; Flags: uninsdeletevalue; Check: not IsAdminInstallMode
Root: HKCU; Subkey: "SOFTWARE\Classes\SFProBrowsHTML\shell\open\command"; Flags: uninsdeletekeyifempty; Check: not IsAdminInstallMode
Root: HKCU; Subkey: "SOFTWARE\Classes\SFProBrowsHTML\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""; Flags: uninsdeletevalue; Check: not IsAdminInstallMode

[Icons]
; Başlat Menüsü Kısayolu (Güvenli ikon eşlemesi eklendi)
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\SFProBrowsIcon.ico"

; Masaüstü Kısayolu (Güvenli ikon eşlemesi eklendi)
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon; IconFilename: "{app}\SFProBrowsIcon.ico"

[Run]
; Kurulum bittiğinde tarayıcıyı çalıştırma seçeneği (%100 dil uyumlu)
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
